name = "flarelytics-dev"
main = "./src/index.ts"
compatibility_date = "2022-02-14"

[vars]
DB_NAME = "dev"

[env.production]
name = "flarelytics"

[env.production.vars]
DB_NAME = "production"

# [secrets]
# REALM_APPID
# REALM_API_TOKEN
